kafka:
  bootstrap:
    servers: localhost:9092

greeting:
  message: "hello"
mp:
  messaging:
    outgoing:
      words-out:
        topic: "words"
        merge: true
    incoming:
      words-in:
        auto:
          offset:
            reset: "earliest"
        topic: "words"
        value:
          deserializer: org.apache.kafka.common.serialization.StringDeserializer
        key:
          deserializer: org.apache.kafka.common.serialization.StringDeserializer
      spring-words-in:
        auto:
          offset:
            reset: "earliest"
        topic: "spring-words"
        value:
          deserializer: org.apache.kafka.common.serialization.StringDeserializer
        key:
          deserializer: org.apache.kafka.common.serialization.StringDeserializer
